package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class aaq {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final biz D;
    public static final bja E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final biz I;
    public static final bja J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final biz N;
    public static final bja O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final biz S;
    public static final bja T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final biz X;
    public static final bja Y;
    public static final long Z;
    public static final bja a;
    public static final long aa;
    public static final long ab;
    public static final biz ac;
    public static final bja ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final biz ah;
    public static final bja ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final biz am;
    public static final bja an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final biz ar;
    public static final bja as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final biz aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final biz e;
    public static final bja f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final biz j;
    public static final bja k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final biz o;
    public static final bja p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final biz t;
    public static final bja u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final biz y;
    public static final bja z;

    static {
        bja bjaVar = aar.a;
        a = aar.b;
        b = bef.h(24.0d);
        c = bef.j(16);
        d = bef.h(0.5d);
        e = aar.d;
        f = aar.b;
        g = bef.h(20.0d);
        h = bef.j(14);
        i = bef.h(0.2d);
        j = aar.d;
        k = aar.b;
        l = bef.h(16.0d);
        m = bef.j(12);
        n = bef.h(0.4d);
        o = aar.d;
        p = aar.a;
        q = bef.h(64.0d);
        r = bef.j(57);
        long h2 = bef.h(0.2d);
        if (!bef.l(h2)) {
            s = bef.k(blp.b(h2), -blp.a(h2));
            t = aar.d;
            u = aar.a;
            v = bef.h(52.0d);
            w = bef.j(45);
            x = bef.h(0.0d);
            y = aar.d;
            z = aar.a;
            A = bef.h(44.0d);
            B = bef.j(36);
            C = bef.h(0.0d);
            D = aar.d;
            E = aar.a;
            F = bef.h(40.0d);
            G = bef.j(32);
            H = bef.h(0.0d);
            I = aar.d;
            J = aar.a;
            K = bef.h(36.0d);
            L = bef.j(28);
            M = bef.h(0.0d);
            N = aar.d;
            O = aar.a;
            P = bef.h(32.0d);
            Q = bef.j(24);
            R = bef.h(0.0d);
            S = aar.d;
            T = aar.b;
            U = bef.h(20.0d);
            V = bef.j(14);
            W = bef.h(0.1d);
            X = aar.c;
            Y = aar.b;
            Z = bef.h(16.0d);
            aa = bef.j(12);
            ab = bef.h(0.5d);
            ac = aar.c;
            ad = aar.b;
            ae = bef.h(16.0d);
            af = bef.j(11);
            ag = bef.h(0.5d);
            ah = aar.c;
            ai = aar.a;
            aj = bef.h(28.0d);
            ak = bef.j(22);
            al = bef.h(0.0d);
            am = aar.d;
            an = aar.b;
            ao = bef.h(24.0d);
            ap = bef.j(16);
            aq = bef.h(0.2d);
            ar = aar.c;
            as = aar.b;
            at = bef.h(20.0d);
            au = bef.j(14);
            av = bef.h(0.1d);
            aw = aar.c;
            return;
        }
        throw new IllegalArgumentException("Cannot perform operation for Unspecified type.");
    }
}
