package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class geu {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final biz D;
    public static final bip E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final biz I;
    public static final bip J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final biz N;
    public static final bip O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final biz S;
    public static final bip T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final biz X;
    public static final bip Y;
    public static final long Z;
    public static final bip a;
    public static final long aa;
    public static final long ab;
    public static final biz ac;
    public static final bip ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final biz ah;
    public static final bip ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final biz am;
    public static final bip an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final biz ar;
    public static final bip as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final biz aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final biz e;
    public static final bip f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final biz j;
    public static final bip k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final biz o;
    public static final bip p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final biz t;
    public static final bip u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final biz y;
    public static final bip z;

    static {
        biz bizVar = gev.a;
        a = gev.d;
        b = bef.h(24.0d);
        c = bef.j(16);
        d = bef.h(0.0d);
        e = gev.b;
        f = gev.d;
        g = bef.h(20.0d);
        h = bef.j(14);
        i = bef.h(0.0d);
        j = gev.b;
        k = gev.d;
        l = bef.h(16.0d);
        m = bef.j(12);
        n = bef.h(0.1d);
        o = gev.b;
        p = gev.c;
        q = bef.h(64.0d);
        r = bef.j(57);
        s = bef.h(0.0d);
        t = gev.b;
        u = gev.c;
        v = bef.h(52.0d);
        w = bef.j(45);
        x = bef.h(0.0d);
        y = gev.b;
        z = gev.c;
        A = bef.h(44.0d);
        B = bef.j(36);
        C = bef.h(0.0d);
        D = gev.b;
        E = gev.c;
        F = bef.h(40.0d);
        G = bef.j(32);
        H = bef.h(0.0d);
        I = gev.b;
        J = gev.c;
        K = bef.h(36.0d);
        L = bef.j(28);
        M = bef.h(0.0d);
        N = gev.b;
        O = gev.c;
        P = bef.h(32.0d);
        Q = bef.j(24);
        R = bef.h(0.0d);
        S = gev.b;
        T = gev.d;
        U = bef.h(20.0d);
        V = bef.j(14);
        W = bef.h(0.0d);
        X = gev.a;
        Y = gev.d;
        Z = bef.h(16.0d);
        aa = bef.j(12);
        ab = bef.h(0.1d);
        ac = gev.a;
        ad = gev.d;
        ae = bef.h(16.0d);
        af = bef.j(11);
        ag = bef.h(0.1d);
        ah = gev.a;
        ai = gev.c;
        aj = bef.h(28.0d);
        ak = bef.j(22);
        al = bef.h(0.0d);
        am = gev.b;
        an = gev.d;
        ao = bef.h(24.0d);
        ap = bef.j(16);
        aq = bef.h(0.0d);
        ar = gev.a;
        as = gev.d;
        at = bef.h(20.0d);
        au = bef.j(14);
        av = bef.h(0.0d);
        aw = gev.a;
    }
}
