package defpackage;

import android.support.design.widget.R;

/* compiled from: PG */
/* loaded from: classes.dex */
public enum lnb implements ljp {
    UNKNOWN_EVENT_TYPE(0),
    LOCATE_REQUESTED(1),
    LOCATE_EXECUTE_ACTION_REQUESTED(215),
    LOCATE_REMOTE_INSTRUCTION_ISSUED(2),
    LOCATE_REMOTE_INSTRUCTION_REQUEST_ERROR(3),
    LOCATE_REMOTE_INSTRUCTION_RECEIVED(35),
    LOCATE_REMOTE_INSTRUCTION_ERROR(40),
    LOCATE_REMOTE_INSTRUCTION_RESULT_SUCCESS(4),
    LOCATE_REMOTE_INSTRUCTION_RESULT_NO_LOCATION(96),
    LOCATE_REMOTE_INSTRUCTION_RESULT_LIVE_LOCATION(28),
    LOCATE_REMOTE_INSTRUCTION_RESULT_LAST_KNOWN_LOCATION(29),
    LOCATE_REMOTE_INSTRUCTION_RESULT_CROWDSOURCED_LOCATION(97),
    LOCATE_REMOTE_INSTRUCTION_RESULT_AGGREGATED_CROWDSOURCED_LOCATION(98),
    LOCATE_REMOTE_INSTRUCTION_RESULT_SEMANTIC_LOCATION(99),
    LOCATE_REMOTE_INSTRUCTION_RESULT_SPOT_LAST_KNOWN_LOCATION(100),
    LOCATE_REMOTE_INSTRUCTION_RESULT_ERROR(5),
    LOCATE_REMOTE_INSTRUCTION_RESULT_FMD_DISABLED(204),
    LOCATE_REMOTE_INSTRUCTION_RESULT_LOCATION_DISABLED(54),
    LOCATE_REMOTE_INSTRUCTION_RESULT_NO_VALID_LOCATION(55),
    LOCATE_REMOTE_INSTRUCTION_RESULT_STALE_LOCATION(56),
    LOCATE_REMOTE_INSTRUCTION_RESULT_ACCESSORY_ERROR(57),
    LOCATE_REMOTE_INSTRUCTION_RESULT_USER_NOT_PRIVILEGED(58),
    LOCATE_REMOTE_INSTRUCTION_RESULT_TIME_OUT(59),
    LOCATE_REMOTE_INSTRUCTION_RESULT_FAILURE(60),
    LOCATE_REMOTE_INSTRUCTION_RESULT_UNKNOWN_ERROR(61),
    LOCATE_REMOTE_INSTRUCTION_SUPERVISED_LOCATION_SHARING_DISABLED(225),
    LOCATE_REMOTE_INSTRUCTION_SUPERVISED_GOOGLE_LOCATION_ACCURACY_DISABLED(226),
    LOCATE_REMOTE_PAYLOAD_REQUEST_ISSUED(44),
    LOCATION_UPDATE_DISPLAYED(216),
    RING_REQUESTED(6),
    RING_REMOTE_INSTRUCTION_ISSUED(7),
    RING_REMOTE_INSTRUCTION_REQUEST_ERROR(8),
    RING_REMOTE_INSTRUCTION_RECEIVED(36),
    RING_REMOTE_INSTRUCTION_RESULT_SUCCESS(9),
    RING_REMOTE_INSTRUCTION_RESULT_DEVICE_INTERRUPTED(10),
    RING_REMOTE_INSTRUCTION_RESULT_ERROR(11),
    RING_LOCAL_INSTRUCTION_ISSUED(101),
    RING_LOCAL_INSTRUCTION_RESULT_SUCCESS(102),
    RING_LOCAL_INSTRUCTION_RESULT_ERROR(103),
    STOP_RINGING_REQUESTED(12),
    STOP_RINGING_REMOTE_INSTRUCTION_ISSUED(13),
    STOP_RINGING_REMOTE_INSTRUCTION_REQUEST_ERROR(14),
    STOP_RINGING_REMOTE_INSTRUCTION_RECEIVED(37),
    STOP_RINGING_REMOTE_INSTRUCTION_RESULT_SUCCESS(15),
    STOP_RINGING_REMOTE_INSTRUCTION_RESULT_ERROR(16),
    STOP_RINGING_LOCAL_INSTRUCTION_ISSUED(104),
    STOP_RINGING_LOCAL_INSTRUCTION_RESULT_SUCCESS(105),
    STOP_RINGING_LOCAL_INSTRUCTION_RESULT_ERROR(106),
    LOCK_REQUESTED(17),
    UPDATE_CONTACT_INFO_FOR_SECURE_DEVICE(67),
    UPDATE_CONTACT_INFO_FOR_SECURE_DEVICE_WHITH_LOST(68),
    LOCK_REMOTE_INSTRUCTION_ISSUED(18),
    LOCK_REMOTE_INSTRUCTION_REQUEST_ERROR(19),
    LOCK_REMOTE_INSTRUCTION_RECEIVED(38),
    LOCK_REMOTE_INSTRUCTION_ERROR(42),
    LOCK_REMOTE_INSTRUCTION_RESULT_SUCCESS(20),
    LOCK_REMOTE_INSTRUCTION_RESULT_UNLOCKED(21),
    LOCK_REMOTE_INSTRUCTION_RESULT_ERROR(22),
    LOCK_REMOTE_INSTRUCTION_RESULT_ERROR_LOCKSCREEN_ALREADY_ENABLED(62),
    LOCK_REMOTE_PAYLOAD_REQUEST_ISSUED(47),
    WIPE_REQUESTED(23),
    WIPE_REMOTE_INSTRUCTION_ISSUED(24),
    WIPE_REMOTE_INSTRUCTION_REQUEST_ERROR(25),
    WIPE_REMOTE_INSTRUCTION_RECEIVED(39),
    WIPE_REMOTE_INSTRUCTION_ERROR(43),
    WIPE_REMOTE_INSTRUCTION_RESULT_SUCCESS(26),
    WIPE_REMOTE_INSTRUCTION_RESULT_ERROR(27),
    WIPE_REMOTE_PAYLOAD_REQUEST_ISSUED(48),
    ERASE_DEVICE_REQUESTED(197),
    ERASE_DEVICE_SUCCESS(198),
    ERASE_DEVICE_ABORTED_LOCATION_DISABLED(199),
    ERASE_DEVICE_ABORTED_PERMISSIONS_DENIED(200),
    ERASE_DEVICE_ABORTED_BLUETOOTH_DISABLED(201),
    ERASE_DEVICE_ABORTED_FORCE_REQUESTED(202),
    ERASE_DEVICE_FAILED(203),
    DEVICE_STATE_UPDATE_RECEIVED_FROM_SERVER(223),
    DEVICE_LOCATION_UPDATED(224),
    SITREP_REMOTE_INSTRUCTION_ISSUED(30),
    SITREP_REMOTE_INSTRUCTION_RECEIVED(31),
    SITREP_REMOTE_INSTRUCTION_ERROR(32),
    SITREP_REMOTE_INSTRUCTION_NO_UPDATE(33),
    SITREP_REQUEST_ISSUED(34),
    REMIND_REMOTE_PAYLOAD_REQUEST_ISSUED(45),
    MARK_LOST(63),
    MARK_LOST_FAILED(206),
    MARK_LOST_REQUESTED(207),
    MARK_FOUND(64),
    MARK_FOUND_FAILED(208),
    MARK_FOUND_REQUESTED(209),
    FOUND_BY_OWNER(65),
    UPDATE_CONTACT_INFO_REQUESTED(210),
    UPDATE_CONTACT_INFO(66),
    UPDATE_CONTACT_INFO_FAILED(211),
    NAVIGATE_REQUESTED(196),
    DPN_REMOTE_INSTRUCTION_ERROR(41),
    DPN_REMOTE_PAYLOAD_REQUEST_ISSUED(46),
    REMOVE_USER_REMOTE_INSTRUCTION_RECEIVED(49),
    REMOVE_USER_REMOTE_INSTRUCTION_RESULT_ERROR(50),
    REMOVE_USER_REMOTE_PAYLOAD_REQUEST_ISSUED(51),
    FIND_MY_DEVICE_UPDATED(52),
    SAMPLED_SETTINGS_SNAPSHOT(53),
    SAMPLED_FIND_MY_DEVICE_MODULE_SETTINGS_SNAPSHOT(205),
    DEVICE_LIST_REFRESH_REQUESTED(212),
    DEVICE_LIST_REFRESHED(94),
    DEVICE_LIST_REFRESH_FAILED(95),
    DEVICE_RENAME_REQUESTED(70),
    DEVICE_RENAME_SUCCESSFUL(71),
    DEVICE_RENAME_CANCELED(72),
    DEVICE_RENAME_FAILURE(91),
    ACTION_ANDROID_MAKE_SOUND_REQUEST_ISSUED(73),
    ACTION_ANDROID_LOCK_SCREEN_REQUEST_ISSUED(74),
    ACTION_ANDROID_SET_LOCK_SCREEN_PASSWORD_REQUEST_ISSUED(92),
    ACTION_ANDROID_LOCATE_REQUEST_ISSUED(75),
    ACTION_ANDROID_STOP_SOUND_REQUEST_ISSUED(76),
    ACTION_ANDROID_WIPE_REQUEST_ISSUED(77),
    ACTION_ANDROID_RENAME_REQUEST_ISSUED(78),
    ACTION_ANDROID_ENABLE_DEVICE_ADMIN_REQUEST_ISSUED(79),
    ACTION_ANDROID_REMIND_REQUEST_ISSUED(80),
    ACTION_ANDROID_SETUP_PROMPT_REQUEST_ISSUED(81),
    ACTION_FAST_PAIR_LOCATE_REQUEST_ISSUED(82),
    ACTION_SPOT_LOCATE_REQUEST_ISSUED(83),
    ACTION_SPOT_MAKE_SOUND_REQUEST_ISSUED(84),
    ACTION_SPOT_STOP_SOUND_REQUEST_ISSUED(85),
    ACTION_SPOT_LOST_REQUEST_ISSUED(86),
    ACTION_SPOT_NOT_LOST_REQUEST_ISSUED(87),
    ACTION_AUTO_DELETE_PROFILE_REQUEST_ISSUED(88),
    ACTION_ANDROID_MAKE_SOUND_REQUEST_FAILED(107),
    ACTION_ANDROID_SET_LOCK_SCREEN_PASSWORD_REQUEST_FAILED(108),
    ACTION_ANDROID_LOCK_SCREEN_REQUEST_FAILED(109),
    ACTION_ANDROID_LOCATE_REQUEST_FAILED(110),
    ACTION_ANDROID_STOP_SOUND_REQUEST_FAILED(111),
    ACTION_ANDROID_WIPE_REQUEST_FAILED(112),
    ACTION_ANDROID_RENAME_REQUEST_FAILED(113),
    ACTION_ANDROID_ENABLE_DEVICE_ADMIN_REQUEST_FAILED(114),
    ACTION_ANDROID_REMIND_REQUEST_FAILED(115),
    ACTION_ANDROID_SETUP_PROMPT_REQUEST_FAILED(116),
    ACTION_FAST_PAIR_LOCATE_REQUEST_FAILED(117),
    ACTION_SPOT_LOCATE_REQUEST_FAILED(118),
    ACTION_SPOT_MAKE_SOUND_REQUEST_FAILED(119),
    ACTION_SPOT_STOP_SOUND_REQUEST_FAILED(120),
    ACTION_SPOT_LOST_REQUEST_FAILED(121),
    ACTION_SPOT_NOT_LOST_REQUEST_FAILED(122),
    ACTION_AUTO_DELETE_PROFILE_REQUEST_FAILED(123),
    SHARING_INVITATION_REQUESTED(124),
    SHARING_INVITATION_GENERATING_LINK(125),
    SHARING_INVITATION_SUCCESS(126),
    SHARING_INVITATION_FAILURE(127),
    SHARING_INVITATION_LINK_GENERATION_FAILURE(213),
    SHARING_APPLICATION_FETCH_INVITATION_REQUESTED(128),
    SHARING_APPLICATION_FETCH_INVITATION_SUCCESS(129),
    SHARING_APPLICATION_USE_RESPONSIBLY_CONFIRMED(140),
    SHARING_APPLICATION_TURN_ON_LOCATION_REQUESTED(141),
    SHARING_APPLICATION_TURN_ON_LOCATION_SUCCESS(142),
    SHARING_APPLICATION_TURN_ON_LOCATION_RESOLVABLE_FAILURE(143),
    SHARING_APPLICATION_TURN_ON_LOCATION_RESOLUTION_FAILED(163),
    SHARING_APPLICATION_TURN_ON_LOCATION_FAILURE(144),
    SHARING_APPLICATION_READ_FIND_MY_DEVICE_SETTINGS_FAILURE(145),
    SHARING_APPLICATION_FIND_MY_DEVICE_SETTINGS_LAUNCHED(166),
    SHARING_APPLICATION_FIND_MY_DEVICE_SETTINGS_FAILED_TO_LAUNCH(167),
    SHARING_APPLICATION_FIND_MY_DEVICE_TURNED_ON(146),
    SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_REQUESTED(147),
    SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_SUCCESS(148),
    SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_RESOLVABLE_FAILURE(149),
    SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_RESOLUTION_FAILED(164),
    SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_FAILURE(150),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_REQUESTED(151),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_SUCCESS(152),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_RESOLVABLE_FAILURE(153),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_RESOLUTION_FAILED(165),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_FAILURE(154),
    SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_SKIPPED(162),
    SHARING_APPLICATION_USER_QUIT_FROM_REQUIREMENTS(161),
    SHARING_APPLICATION_REQUIREMENTS_LAUNCHED(158),
    SHARING_APPLICATION_REQUIREMENTS_MET(159),
    SHARING_APPLICATION_REQUIREMENTS_NOT_MET(160),
    SHARING_APPLICATION_USER_APPLY_REQUESTED(155),
    SHARING_APPLICATION_USER_APPLY_SUCCESS(156),
    SHARING_APPLICATION_USER_DECLINED(157),
    SHARING_APPLICATION_OWNER_KEY_RESOLUTION_REQUESTED(132),
    SHARING_APPLICATION_OWNER_KEY_RESOLUTION_SUCCESS(133),
    SHARING_APPLICATION_OWNER_KEY_RESOLUTION_FAILURE(134),
    SHARING_APPLICATION_SCREEN_LOCK_CHECK_REQUESTED(217),
    SHARING_APPLICATION_SCREEN_LOCK_NEEDED(218),
    SHARING_APPLICATION_SCREEN_LOCK_ALREADY_SET(219),
    SHARING_APPLICATION_SCREEN_LOCK_CHECK_FAILURE(220),
    SHARING_APPLICATION_SCREEN_LOCK_ACTIVITY_STARTED_SUCCESSFULLY(221),
    SHARING_APPLICATION_SCREEN_LOCK_ACTIVITY_STARTED_FAILURE(222),
    SHARING_APPLICATION_SCREEN_LOCK_SET(135),
    SHARING_APPLICATION_FAILURE(136),
    SHARING_APPLICATION_FAILURE_LSKF_NOT_SUPPORTED(137),
    SHARING_APPLICATION_FAILURE_SCREEN_LOCK_REQUIRED(138),
    SHARING_APPLICATION_FAILURE_SYNC_OWNER_KEY_REQUIRED(139),
    SHARING_APPLICATION_GENERAL_KEYCHAIN_FAILURE(214),
    SHARING_PENDING_CALCULATING_VALIDATION_CODE_STARTED(168),
    SHARING_PENDING_CALCULATING_VALIDATION_CODE_SUCCESS(169),
    SHARING_PENDING_CALCULATING_VALIDATION_CODE_FAILURE(170),
    SHARING_PENDING_CALCULATING_VALIDATION_CODE_UNAVAILABLE_BECAUSE_ALREADY_APPROVED(171),
    SHARING_FINALIZATION_START(172),
    SHARING_FINALIZATION_SUCCESS(173),
    SHARING_FINALIZATION_FAILURE(174),
    SHARING_PENDING_WITHDRAW_REQUESTED(175),
    SHARING_PENDING_WITHDRAW_SUCCESS(176),
    SHARING_PENDING_WITHDRAW_FAILURE(177),
    SHARING_APPLICATION_APPROVAL_CALCILATING_VALIDATION_CODE_STARTED(178),
    SHARING_APPLICATION_APPROVAL_CALCULATING_VALIDATION_CODE_SUCCESS(179),
    SHARING_APPLICATION_APPROVAL_CALCULATING_VALIDATION_CODE_FAILURE(180),
    SHARING_APPLICATION_APPROVAL_APPROVE_REQUESTED(181),
    SHARING_APPLICATION_APPROVAL_APPROVE_SUCCESS(182),
    SHARING_APPLICATION_APPROVAL_APPROVE_FAILURE(183),
    SHARING_APPLICATION_APPROVAL_DECLINE_REQUESTED(184),
    SHARING_APPLICATION_APPROVAL_DECLINE_SUCCESS(185),
    SHARING_APPLICATION_APPROVAL_DECLINE_FAILURE(186),
    REFRESH_SHARED_OWNERS_LIST_REQUESTED(187),
    REFRESH_SHARED_OWNERS_LIST_SUCCESS(188),
    REFRESH_SHARED_OWNERS_LIST_FAILURE(189),
    REVOKE_SHARED_OWNER_REQUESTED(190),
    REVOKE_SHARED_OWNER_SUCCESS(191),
    REVOKE_SHARED_OWNER_FAILURE(192),
    RELINQUISH_SHARED_OWNERSHIP_REQUESTED(193),
    RELINQUISH_SHARED_OWNERSHIP_SUCCESS(194),
    RELINQUISH_SHARED_OWNERSHIP_FAILURE(195),
    QUICK_REMOTE_LOCK_REQUESTED(227),
    QUICK_REMOTE_LOCK_DEVICE_UNLOCKED(228),
    QUICK_REMOTE_LOCK_NOTIFICATION_CLICKED(229),
    QUICK_REMOTE_LOCK_NOTIFICATION_DISMISSED(230),
    QUICK_REMOTE_LOCK_PAGE_OPENED(231),
    QUICK_REMOTE_LOCK_STATUS_SHOWN(232),
    QUICK_REMOTE_LOCK_TOGGLED(233),
    QUICK_REMOTE_LOCK_PERIODIC(272),
    LOCATION_SHARING_LAUNCH_SHARE_CREATION_DIALOG(234),
    LOCATION_SHARING_CANCEL_SHARE_CREATION(235),
    LOCATION_SHARING_CLICK_SHOW_SHARE_CREATION_DIALOG(236),
    LOCATION_SHARING_CLICK_CREATE_SHARE(237),
    LOCATION_SHARING_CREATE_SHARE_FAILURE(238),
    LOCATION_SHARING_COMPLETE_SHARE_CREATION(239),
    LOCATION_SHARING_GET_SHARE_FAILURE(240),
    LOCATION_SHARING_SHARE_DETAIL_SHOWN(241),
    LOCATION_SHARING_SHARE_LIST_SHOWN(242),
    LOCATION_SHARING_ONBOARDING_SHOWN(243),
    LOCATION_SHARING_CLICK_GET_DIRECTIONS(244),
    LOCATION_SHARING_CLICK_HIDE(245),
    LOCATION_SHARING_CONFIRM_HIDE(246),
    LOCATION_SHARING_CANCEL_HIDE(247),
    LOCATION_SHARING_CLICK_UNHIDE(248),
    LOCATION_SHARING_CLICK_BLOCK(249),
    LOCATION_SHARING_CONFIRM_BLOCK(250),
    LOCATION_SHARING_CANCEL_BLOCK(251),
    LOCATION_SHARING_CLICK_REFRESH(252),
    LOCATION_SHARING_CLICK_STOP(253),
    LOCATION_SHARING_CLICK_CONFIRM_STOP_SHARE(254),
    LOCATION_SHARING_CLICK_CANCEL_STOP_SHARE(255),
    LOCATION_SHARING_CLICK_COPY_SHARE_LINK(256),
    SUGGESTED_ACTION_CARD_SHOWN(257),
    SUGGESTED_ACTION_CLICK_CARD_ACTION(258),
    CENTRALIZED_LOCATION_SHARING_MIGRATION_NOTICE_SHOWN(259),
    CENTRALIZED_LOCATION_SHARING_ACCEPT_MIGRATION(260),
    CENTRALIZED_LOCATION_SHARING_DEFER_MIGRATION(261),
    ACTION_CLICK_CENTER_MY_LOCATION(262),
    ACTION_CLICK_CENTER_MY_LOCATION_WITHOUT_PERMISSIONS(263),
    ACTION_CLICK_CENTER_MY_LOCATION_WHEN_LOCATION_IS_DISABLED(264),
    ACTION_CENTER_MY_LOCATION_PERMISSIONS_GRANTED(265),
    ACTION_CENTER_MY_LOCATION_PERMISSIONS_DENIED(266),
    ACTION_CLICK_PEOPLE_TAB(267),
    ACTION_CLICK_DEVICES_TAB(268),
    ACTION_PEOPLE_PAGE_SHOWN(269),
    ACTION_DEVICES_PAGE_SHOWN(270),
    ACTION_CLICK_LEARN_MORE_LINK(271);

    public final int eh;

    lnb(int i) {
        this.eh = i;
    }

    public static lnb b(int i) {
        switch (i) {
            case 0:
                return UNKNOWN_EVENT_TYPE;
            case 1:
                return LOCATE_REQUESTED;
            case 2:
                return LOCATE_REMOTE_INSTRUCTION_ISSUED;
            case 3:
                return LOCATE_REMOTE_INSTRUCTION_REQUEST_ERROR;
            case 4:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_SUCCESS;
            case 5:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_ERROR;
            case 6:
                return RING_REQUESTED;
            case 7:
                return RING_REMOTE_INSTRUCTION_ISSUED;
            case 8:
                return RING_REMOTE_INSTRUCTION_REQUEST_ERROR;
            case 9:
                return RING_REMOTE_INSTRUCTION_RESULT_SUCCESS;
            case 10:
                return RING_REMOTE_INSTRUCTION_RESULT_DEVICE_INTERRUPTED;
            case 11:
                return RING_REMOTE_INSTRUCTION_RESULT_ERROR;
            case 12:
                return STOP_RINGING_REQUESTED;
            case 13:
                return STOP_RINGING_REMOTE_INSTRUCTION_ISSUED;
            case 14:
                return STOP_RINGING_REMOTE_INSTRUCTION_REQUEST_ERROR;
            case 15:
                return STOP_RINGING_REMOTE_INSTRUCTION_RESULT_SUCCESS;
            case 16:
                return STOP_RINGING_REMOTE_INSTRUCTION_RESULT_ERROR;
            case 17:
                return LOCK_REQUESTED;
            case 18:
                return LOCK_REMOTE_INSTRUCTION_ISSUED;
            case 19:
                return LOCK_REMOTE_INSTRUCTION_REQUEST_ERROR;
            case 20:
                return LOCK_REMOTE_INSTRUCTION_RESULT_SUCCESS;
            case 21:
                return LOCK_REMOTE_INSTRUCTION_RESULT_UNLOCKED;
            case 22:
                return LOCK_REMOTE_INSTRUCTION_RESULT_ERROR;
            case 23:
                return WIPE_REQUESTED;
            case R.styleable.TextInputLayout_cursorColor /* 24 */:
                return WIPE_REMOTE_INSTRUCTION_ISSUED;
            case R.styleable.TextInputLayout_cursorErrorColor /* 25 */:
                return WIPE_REMOTE_INSTRUCTION_REQUEST_ERROR;
            case R.styleable.TextInputLayout_endIconCheckable /* 26 */:
                return WIPE_REMOTE_INSTRUCTION_RESULT_SUCCESS;
            case R.styleable.TextInputLayout_endIconContentDescription /* 27 */:
                return WIPE_REMOTE_INSTRUCTION_RESULT_ERROR;
            case R.styleable.TextInputLayout_endIconDrawable /* 28 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_LIVE_LOCATION;
            case R.styleable.TextInputLayout_endIconMinSize /* 29 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_LAST_KNOWN_LOCATION;
            case R.styleable.TextInputLayout_endIconMode /* 30 */:
                return SITREP_REMOTE_INSTRUCTION_ISSUED;
            case R.styleable.TextInputLayout_endIconScaleType /* 31 */:
                return SITREP_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_endIconTint /* 32 */:
                return SITREP_REMOTE_INSTRUCTION_ERROR;
            case R.styleable.TextInputLayout_endIconTintMode /* 33 */:
                return SITREP_REMOTE_INSTRUCTION_NO_UPDATE;
            case R.styleable.TextInputLayout_errorAccessibilityLiveRegion /* 34 */:
                return SITREP_REQUEST_ISSUED;
            case 35:
                return LOCATE_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_errorEnabled /* 36 */:
                return RING_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_errorIconDrawable /* 37 */:
                return STOP_RINGING_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_errorIconTint /* 38 */:
                return LOCK_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_errorIconTintMode /* 39 */:
                return WIPE_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_errorTextAppearance /* 40 */:
                return LOCATE_REMOTE_INSTRUCTION_ERROR;
            case R.styleable.TextInputLayout_errorTextColor /* 41 */:
                return DPN_REMOTE_INSTRUCTION_ERROR;
            case R.styleable.TextInputLayout_expandedHintEnabled /* 42 */:
                return LOCK_REMOTE_INSTRUCTION_ERROR;
            case R.styleable.TextInputLayout_helperText /* 43 */:
                return WIPE_REMOTE_INSTRUCTION_ERROR;
            case R.styleable.TextInputLayout_helperTextEnabled /* 44 */:
                return LOCATE_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_helperTextTextAppearance /* 45 */:
                return REMIND_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_helperTextTextColor /* 46 */:
                return DPN_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_hintAnimationEnabled /* 47 */:
                return LOCK_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_hintEnabled /* 48 */:
                return WIPE_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_hintTextAppearance /* 49 */:
                return REMOVE_USER_REMOTE_INSTRUCTION_RECEIVED;
            case R.styleable.TextInputLayout_hintTextColor /* 50 */:
                return REMOVE_USER_REMOTE_INSTRUCTION_RESULT_ERROR;
            case R.styleable.TextInputLayout_passwordToggleContentDescription /* 51 */:
                return REMOVE_USER_REMOTE_PAYLOAD_REQUEST_ISSUED;
            case R.styleable.TextInputLayout_passwordToggleDrawable /* 52 */:
                return FIND_MY_DEVICE_UPDATED;
            case R.styleable.TextInputLayout_passwordToggleEnabled /* 53 */:
                return SAMPLED_SETTINGS_SNAPSHOT;
            case R.styleable.TextInputLayout_passwordToggleTint /* 54 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_LOCATION_DISABLED;
            case R.styleable.TextInputLayout_passwordToggleTintMode /* 55 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_NO_VALID_LOCATION;
            case R.styleable.TextInputLayout_placeholderText /* 56 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_STALE_LOCATION;
            case R.styleable.TextInputLayout_placeholderTextAppearance /* 57 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_ACCESSORY_ERROR;
            case R.styleable.TextInputLayout_placeholderTextColor /* 58 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_USER_NOT_PRIVILEGED;
            case R.styleable.TextInputLayout_prefixText /* 59 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_TIME_OUT;
            case R.styleable.TextInputLayout_prefixTextAppearance /* 60 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_FAILURE;
            case R.styleable.TextInputLayout_prefixTextColor /* 61 */:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_UNKNOWN_ERROR;
            case R.styleable.TextInputLayout_shapeAppearance /* 62 */:
                return LOCK_REMOTE_INSTRUCTION_RESULT_ERROR_LOCKSCREEN_ALREADY_ENABLED;
            case R.styleable.TextInputLayout_shapeAppearanceOverlay /* 63 */:
                return MARK_LOST;
            case R.styleable.TextInputLayout_startIconCheckable /* 64 */:
                return MARK_FOUND;
            case R.styleable.TextInputLayout_startIconContentDescription /* 65 */:
                return FOUND_BY_OWNER;
            case R.styleable.TextInputLayout_startIconDrawable /* 66 */:
                return UPDATE_CONTACT_INFO;
            case R.styleable.TextInputLayout_startIconMinSize /* 67 */:
                return UPDATE_CONTACT_INFO_FOR_SECURE_DEVICE;
            case R.styleable.TextInputLayout_startIconScaleType /* 68 */:
                return UPDATE_CONTACT_INFO_FOR_SECURE_DEVICE_WHITH_LOST;
            case R.styleable.TextInputLayout_startIconTint /* 69 */:
            case 89:
            case 90:
            case 93:
            case 130:
            case 131:
            default:
                return null;
            case R.styleable.TextInputLayout_startIconTintMode /* 70 */:
                return DEVICE_RENAME_REQUESTED;
            case R.styleable.TextInputLayout_suffixText /* 71 */:
                return DEVICE_RENAME_SUCCESSFUL;
            case R.styleable.TextInputLayout_suffixTextAppearance /* 72 */:
                return DEVICE_RENAME_CANCELED;
            case R.styleable.TextInputLayout_suffixTextColor /* 73 */:
                return ACTION_ANDROID_MAKE_SOUND_REQUEST_ISSUED;
            case 74:
                return ACTION_ANDROID_LOCK_SCREEN_REQUEST_ISSUED;
            case 75:
                return ACTION_ANDROID_LOCATE_REQUEST_ISSUED;
            case 76:
                return ACTION_ANDROID_STOP_SOUND_REQUEST_ISSUED;
            case 77:
                return ACTION_ANDROID_WIPE_REQUEST_ISSUED;
            case 78:
                return ACTION_ANDROID_RENAME_REQUEST_ISSUED;
            case 79:
                return ACTION_ANDROID_ENABLE_DEVICE_ADMIN_REQUEST_ISSUED;
            case 80:
                return ACTION_ANDROID_REMIND_REQUEST_ISSUED;
            case 81:
                return ACTION_ANDROID_SETUP_PROMPT_REQUEST_ISSUED;
            case 82:
                return ACTION_FAST_PAIR_LOCATE_REQUEST_ISSUED;
            case 83:
                return ACTION_SPOT_LOCATE_REQUEST_ISSUED;
            case 84:
                return ACTION_SPOT_MAKE_SOUND_REQUEST_ISSUED;
            case 85:
                return ACTION_SPOT_STOP_SOUND_REQUEST_ISSUED;
            case 86:
                return ACTION_SPOT_LOST_REQUEST_ISSUED;
            case 87:
                return ACTION_SPOT_NOT_LOST_REQUEST_ISSUED;
            case 88:
                return ACTION_AUTO_DELETE_PROFILE_REQUEST_ISSUED;
            case 91:
                return DEVICE_RENAME_FAILURE;
            case 92:
                return ACTION_ANDROID_SET_LOCK_SCREEN_PASSWORD_REQUEST_ISSUED;
            case 94:
                return DEVICE_LIST_REFRESHED;
            case 95:
                return DEVICE_LIST_REFRESH_FAILED;
            case 96:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_NO_LOCATION;
            case 97:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_CROWDSOURCED_LOCATION;
            case 98:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_AGGREGATED_CROWDSOURCED_LOCATION;
            case 99:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_SEMANTIC_LOCATION;
            case 100:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_SPOT_LAST_KNOWN_LOCATION;
            case 101:
                return RING_LOCAL_INSTRUCTION_ISSUED;
            case 102:
                return RING_LOCAL_INSTRUCTION_RESULT_SUCCESS;
            case 103:
                return RING_LOCAL_INSTRUCTION_RESULT_ERROR;
            case 104:
                return STOP_RINGING_LOCAL_INSTRUCTION_ISSUED;
            case 105:
                return STOP_RINGING_LOCAL_INSTRUCTION_RESULT_SUCCESS;
            case 106:
                return STOP_RINGING_LOCAL_INSTRUCTION_RESULT_ERROR;
            case 107:
                return ACTION_ANDROID_MAKE_SOUND_REQUEST_FAILED;
            case 108:
                return ACTION_ANDROID_SET_LOCK_SCREEN_PASSWORD_REQUEST_FAILED;
            case 109:
                return ACTION_ANDROID_LOCK_SCREEN_REQUEST_FAILED;
            case 110:
                return ACTION_ANDROID_LOCATE_REQUEST_FAILED;
            case 111:
                return ACTION_ANDROID_STOP_SOUND_REQUEST_FAILED;
            case 112:
                return ACTION_ANDROID_WIPE_REQUEST_FAILED;
            case 113:
                return ACTION_ANDROID_RENAME_REQUEST_FAILED;
            case 114:
                return ACTION_ANDROID_ENABLE_DEVICE_ADMIN_REQUEST_FAILED;
            case 115:
                return ACTION_ANDROID_REMIND_REQUEST_FAILED;
            case 116:
                return ACTION_ANDROID_SETUP_PROMPT_REQUEST_FAILED;
            case 117:
                return ACTION_FAST_PAIR_LOCATE_REQUEST_FAILED;
            case 118:
                return ACTION_SPOT_LOCATE_REQUEST_FAILED;
            case 119:
                return ACTION_SPOT_MAKE_SOUND_REQUEST_FAILED;
            case 120:
                return ACTION_SPOT_STOP_SOUND_REQUEST_FAILED;
            case 121:
                return ACTION_SPOT_LOST_REQUEST_FAILED;
            case 122:
                return ACTION_SPOT_NOT_LOST_REQUEST_FAILED;
            case 123:
                return ACTION_AUTO_DELETE_PROFILE_REQUEST_FAILED;
            case 124:
                return SHARING_INVITATION_REQUESTED;
            case 125:
                return SHARING_INVITATION_GENERATING_LINK;
            case 126:
                return SHARING_INVITATION_SUCCESS;
            case 127:
                return SHARING_INVITATION_FAILURE;
            case 128:
                return SHARING_APPLICATION_FETCH_INVITATION_REQUESTED;
            case 129:
                return SHARING_APPLICATION_FETCH_INVITATION_SUCCESS;
            case 132:
                return SHARING_APPLICATION_OWNER_KEY_RESOLUTION_REQUESTED;
            case 133:
                return SHARING_APPLICATION_OWNER_KEY_RESOLUTION_SUCCESS;
            case 134:
                return SHARING_APPLICATION_OWNER_KEY_RESOLUTION_FAILURE;
            case 135:
                return SHARING_APPLICATION_SCREEN_LOCK_SET;
            case 136:
                return SHARING_APPLICATION_FAILURE;
            case 137:
                return SHARING_APPLICATION_FAILURE_LSKF_NOT_SUPPORTED;
            case 138:
                return SHARING_APPLICATION_FAILURE_SCREEN_LOCK_REQUIRED;
            case 139:
                return SHARING_APPLICATION_FAILURE_SYNC_OWNER_KEY_REQUIRED;
            case 140:
                return SHARING_APPLICATION_USE_RESPONSIBLY_CONFIRMED;
            case 141:
                return SHARING_APPLICATION_TURN_ON_LOCATION_REQUESTED;
            case 142:
                return SHARING_APPLICATION_TURN_ON_LOCATION_SUCCESS;
            case 143:
                return SHARING_APPLICATION_TURN_ON_LOCATION_RESOLVABLE_FAILURE;
            case 144:
                return SHARING_APPLICATION_TURN_ON_LOCATION_FAILURE;
            case 145:
                return SHARING_APPLICATION_READ_FIND_MY_DEVICE_SETTINGS_FAILURE;
            case 146:
                return SHARING_APPLICATION_FIND_MY_DEVICE_TURNED_ON;
            case 147:
                return SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_REQUESTED;
            case 148:
                return SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_SUCCESS;
            case 149:
                return SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_RESOLVABLE_FAILURE;
            case 150:
                return SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_FAILURE;
            case 151:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_REQUESTED;
            case 152:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_SUCCESS;
            case 153:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_RESOLVABLE_FAILURE;
            case 154:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_FAILURE;
            case 155:
                return SHARING_APPLICATION_USER_APPLY_REQUESTED;
            case 156:
                return SHARING_APPLICATION_USER_APPLY_SUCCESS;
            case 157:
                return SHARING_APPLICATION_USER_DECLINED;
            case 158:
                return SHARING_APPLICATION_REQUIREMENTS_LAUNCHED;
            case 159:
                return SHARING_APPLICATION_REQUIREMENTS_MET;
            case 160:
                return SHARING_APPLICATION_REQUIREMENTS_NOT_MET;
            case 161:
                return SHARING_APPLICATION_USER_QUIT_FROM_REQUIREMENTS;
            case 162:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_SKIPPED;
            case 163:
                return SHARING_APPLICATION_TURN_ON_LOCATION_RESOLUTION_FAILED;
            case 164:
                return SHARING_APPLICATION_TURN_LAST_KNOWN_LOCATION_ON_RESOLUTION_FAILED;
            case 165:
                return SHARING_APPLICATION_JOIN_FIND_MY_DEVICE_NETWORK_RESOLUTION_FAILED;
            case 166:
                return SHARING_APPLICATION_FIND_MY_DEVICE_SETTINGS_LAUNCHED;
            case 167:
                return SHARING_APPLICATION_FIND_MY_DEVICE_SETTINGS_FAILED_TO_LAUNCH;
            case 168:
                return SHARING_PENDING_CALCULATING_VALIDATION_CODE_STARTED;
            case 169:
                return SHARING_PENDING_CALCULATING_VALIDATION_CODE_SUCCESS;
            case 170:
                return SHARING_PENDING_CALCULATING_VALIDATION_CODE_FAILURE;
            case 171:
                return SHARING_PENDING_CALCULATING_VALIDATION_CODE_UNAVAILABLE_BECAUSE_ALREADY_APPROVED;
            case 172:
                return SHARING_FINALIZATION_START;
            case 173:
                return SHARING_FINALIZATION_SUCCESS;
            case 174:
                return SHARING_FINALIZATION_FAILURE;
            case 175:
                return SHARING_PENDING_WITHDRAW_REQUESTED;
            case 176:
                return SHARING_PENDING_WITHDRAW_SUCCESS;
            case 177:
                return SHARING_PENDING_WITHDRAW_FAILURE;
            case 178:
                return SHARING_APPLICATION_APPROVAL_CALCILATING_VALIDATION_CODE_STARTED;
            case 179:
                return SHARING_APPLICATION_APPROVAL_CALCULATING_VALIDATION_CODE_SUCCESS;
            case 180:
                return SHARING_APPLICATION_APPROVAL_CALCULATING_VALIDATION_CODE_FAILURE;
            case 181:
                return SHARING_APPLICATION_APPROVAL_APPROVE_REQUESTED;
            case 182:
                return SHARING_APPLICATION_APPROVAL_APPROVE_SUCCESS;
            case 183:
                return SHARING_APPLICATION_APPROVAL_APPROVE_FAILURE;
            case 184:
                return SHARING_APPLICATION_APPROVAL_DECLINE_REQUESTED;
            case 185:
                return SHARING_APPLICATION_APPROVAL_DECLINE_SUCCESS;
            case 186:
                return SHARING_APPLICATION_APPROVAL_DECLINE_FAILURE;
            case 187:
                return REFRESH_SHARED_OWNERS_LIST_REQUESTED;
            case 188:
                return REFRESH_SHARED_OWNERS_LIST_SUCCESS;
            case 189:
                return REFRESH_SHARED_OWNERS_LIST_FAILURE;
            case 190:
                return REVOKE_SHARED_OWNER_REQUESTED;
            case 191:
                return REVOKE_SHARED_OWNER_SUCCESS;
            case 192:
                return REVOKE_SHARED_OWNER_FAILURE;
            case 193:
                return RELINQUISH_SHARED_OWNERSHIP_REQUESTED;
            case 194:
                return RELINQUISH_SHARED_OWNERSHIP_SUCCESS;
            case 195:
                return RELINQUISH_SHARED_OWNERSHIP_FAILURE;
            case 196:
                return NAVIGATE_REQUESTED;
            case 197:
                return ERASE_DEVICE_REQUESTED;
            case 198:
                return ERASE_DEVICE_SUCCESS;
            case 199:
                return ERASE_DEVICE_ABORTED_LOCATION_DISABLED;
            case 200:
                return ERASE_DEVICE_ABORTED_PERMISSIONS_DENIED;
            case 201:
                return ERASE_DEVICE_ABORTED_BLUETOOTH_DISABLED;
            case 202:
                return ERASE_DEVICE_ABORTED_FORCE_REQUESTED;
            case 203:
                return ERASE_DEVICE_FAILED;
            case 204:
                return LOCATE_REMOTE_INSTRUCTION_RESULT_FMD_DISABLED;
            case 205:
                return SAMPLED_FIND_MY_DEVICE_MODULE_SETTINGS_SNAPSHOT;
            case 206:
                return MARK_LOST_FAILED;
            case 207:
                return MARK_LOST_REQUESTED;
            case 208:
                return MARK_FOUND_FAILED;
            case 209:
                return MARK_FOUND_REQUESTED;
            case 210:
                return UPDATE_CONTACT_INFO_REQUESTED;
            case 211:
                return UPDATE_CONTACT_INFO_FAILED;
            case 212:
                return DEVICE_LIST_REFRESH_REQUESTED;
            case 213:
                return SHARING_INVITATION_LINK_GENERATION_FAILURE;
            case 214:
                return SHARING_APPLICATION_GENERAL_KEYCHAIN_FAILURE;
            case 215:
                return LOCATE_EXECUTE_ACTION_REQUESTED;
            case 216:
                return LOCATION_UPDATE_DISPLAYED;
            case 217:
                return SHARING_APPLICATION_SCREEN_LOCK_CHECK_REQUESTED;
            case 218:
                return SHARING_APPLICATION_SCREEN_LOCK_NEEDED;
            case 219:
                return SHARING_APPLICATION_SCREEN_LOCK_ALREADY_SET;
            case 220:
                return SHARING_APPLICATION_SCREEN_LOCK_CHECK_FAILURE;
            case 221:
                return SHARING_APPLICATION_SCREEN_LOCK_ACTIVITY_STARTED_SUCCESSFULLY;
            case 222:
                return SHARING_APPLICATION_SCREEN_LOCK_ACTIVITY_STARTED_FAILURE;
            case 223:
                return DEVICE_STATE_UPDATE_RECEIVED_FROM_SERVER;
            case 224:
                return DEVICE_LOCATION_UPDATED;
            case 225:
                return LOCATE_REMOTE_INSTRUCTION_SUPERVISED_LOCATION_SHARING_DISABLED;
            case 226:
                return LOCATE_REMOTE_INSTRUCTION_SUPERVISED_GOOGLE_LOCATION_ACCURACY_DISABLED;
            case 227:
                return QUICK_REMOTE_LOCK_REQUESTED;
            case 228:
                return QUICK_REMOTE_LOCK_DEVICE_UNLOCKED;
            case 229:
                return QUICK_REMOTE_LOCK_NOTIFICATION_CLICKED;
            case 230:
                return QUICK_REMOTE_LOCK_NOTIFICATION_DISMISSED;
            case 231:
                return QUICK_REMOTE_LOCK_PAGE_OPENED;
            case 232:
                return QUICK_REMOTE_LOCK_STATUS_SHOWN;
            case 233:
                return QUICK_REMOTE_LOCK_TOGGLED;
            case 234:
                return LOCATION_SHARING_LAUNCH_SHARE_CREATION_DIALOG;
            case 235:
                return LOCATION_SHARING_CANCEL_SHARE_CREATION;
            case 236:
                return LOCATION_SHARING_CLICK_SHOW_SHARE_CREATION_DIALOG;
            case 237:
                return LOCATION_SHARING_CLICK_CREATE_SHARE;
            case 238:
                return LOCATION_SHARING_CREATE_SHARE_FAILURE;
            case 239:
                return LOCATION_SHARING_COMPLETE_SHARE_CREATION;
            case 240:
                return LOCATION_SHARING_GET_SHARE_FAILURE;
            case 241:
                return LOCATION_SHARING_SHARE_DETAIL_SHOWN;
            case 242:
                return LOCATION_SHARING_SHARE_LIST_SHOWN;
            case 243:
                return LOCATION_SHARING_ONBOARDING_SHOWN;
            case 244:
                return LOCATION_SHARING_CLICK_GET_DIRECTIONS;
            case 245:
                return LOCATION_SHARING_CLICK_HIDE;
            case 246:
                return LOCATION_SHARING_CONFIRM_HIDE;
            case 247:
                return LOCATION_SHARING_CANCEL_HIDE;
            case 248:
                return LOCATION_SHARING_CLICK_UNHIDE;
            case 249:
                return LOCATION_SHARING_CLICK_BLOCK;
            case 250:
                return LOCATION_SHARING_CONFIRM_BLOCK;
            case 251:
                return LOCATION_SHARING_CANCEL_BLOCK;
            case 252:
                return LOCATION_SHARING_CLICK_REFRESH;
            case 253:
                return LOCATION_SHARING_CLICK_STOP;
            case 254:
                return LOCATION_SHARING_CLICK_CONFIRM_STOP_SHARE;
            case 255:
                return LOCATION_SHARING_CLICK_CANCEL_STOP_SHARE;
            case 256:
                return LOCATION_SHARING_CLICK_COPY_SHARE_LINK;
            case 257:
                return SUGGESTED_ACTION_CARD_SHOWN;
            case 258:
                return SUGGESTED_ACTION_CLICK_CARD_ACTION;
            case 259:
                return CENTRALIZED_LOCATION_SHARING_MIGRATION_NOTICE_SHOWN;
            case 260:
                return CENTRALIZED_LOCATION_SHARING_ACCEPT_MIGRATION;
            case 261:
                return CENTRALIZED_LOCATION_SHARING_DEFER_MIGRATION;
            case 262:
                return ACTION_CLICK_CENTER_MY_LOCATION;
            case 263:
                return ACTION_CLICK_CENTER_MY_LOCATION_WITHOUT_PERMISSIONS;
            case 264:
                return ACTION_CLICK_CENTER_MY_LOCATION_WHEN_LOCATION_IS_DISABLED;
            case 265:
                return ACTION_CENTER_MY_LOCATION_PERMISSIONS_GRANTED;
            case 266:
                return ACTION_CENTER_MY_LOCATION_PERMISSIONS_DENIED;
            case 267:
                return ACTION_CLICK_PEOPLE_TAB;
            case 268:
                return ACTION_CLICK_DEVICES_TAB;
            case 269:
                return ACTION_PEOPLE_PAGE_SHOWN;
            case 270:
                return ACTION_DEVICES_PAGE_SHOWN;
            case 271:
                return ACTION_CLICK_LEARN_MORE_LINK;
            case 272:
                return QUICK_REMOTE_LOCK_PERIODIC;
        }
    }

    @Override // defpackage.ljp
    public final int a() {
        return this.eh;
    }

    @Override // java.lang.Enum
    public final String toString() {
        return Integer.toString(this.eh);
    }
}
