package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class lwg implements lwf {
    public static final hxo a;

    static {
        jmo jmoVar = jmo.a;
        a = hxs.c("45357579", 57600000L, "com.google.android.libraries.notifications.platform", jjr.s("ANDROID_GROWTH", "STREAMZ_ANDROID_GROWTH", "CHIME", "PHOTOS_ANDROID_PRIMES", "YT_MAIN_APP_ANDROID_PRIMES", "ANDROID_GSA_ANDROID_PRIMES", "GMM_PRIMES", "ANDROID_CONTACTS_PRIMES", "DOCS_ANDROID_PRIMES", "DRIVE_ANDROID_PRIMES", "CALENDAR_ANDROID_PRIMES", "DIALER_ANDROID_PRIMES", "ANDROID_MESSAGING_PRIMES", "TACHYON_ANDROID_PRIMES", "DYNAMITE_ANDROID_PRIMES", "GMAIL_ANDROID_PRIMES", "PAISA_MERCHANT_ANDROID_PRIMES", "STREAMZ_GNP_ANDROID", "MEETINGS_ANDROID_PRIMES", "FITNESS_ANDROID_PRIMES", "MEDIA_HOME_ANDROID_PRIMES", "TASKS_ANDROID_PRIMES", "GOR_ANDROID_PRIMES", "PLAY_GAMES_ANDROID_PRIMES", "NOVA_ANDROID_PRIMES", "FAMILYLINK_ANDROID_PRIMES", "KEEP_ANDROID_PRIMES", "TRANSLATE_ANDROID_PRIMES", "CHROMECAST_ANDROID_APP_PRIMES", "GOOGLE_RED_ANDROID_PRIMES", "PAISA_FLUTTER_ANDROID_PRIMES", "ADWORDS_FLUTTER_ANDROID_PRIMES", "CULTURAL_ANDROID_PRIMES", "PLAY_MOVIES_ANDROID_PRIMES", "FILESGO_ANDROID_PRIMES"), true, false, false);
    }

    @Override // defpackage.lwf
    public final long a() {
        return ((Long) a.a()).longValue();
    }
}
